<?php

if (empty($params['case']))
	{
	$result['respon']['pesan'] == "gagal";
	$result['respon']['pesan'] == "Module tidak dapat di muat";
	echo json_encode($result);
	exit();
	}


			$input = $params['input_option'];

      $sql_f = "SELECT KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_LAPORAN FROM KPE_AIR_FLOWMETER_OPERASIONAL_PRE WHERE KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL='".$input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL']."' AND RECORD_STATUS='A'";

      $this->MYSQL = new MYSQL();
      $this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
      $this->MYSQL->queri = $sql_f;
      $result_f = $this->MYSQL->data();

      $sql_e = "SELECT * FROM KPE_AIR_FLOWMETER_KIMIA_PRE WHERE KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL='".$input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL_SEBELUMNYA']."' AND RECORD_STATUS='A'";

      $this->MYSQL = new MYSQL();
      $this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
      $this->MYSQL->queri = $sql_e;
      $result_e = $this->MYSQL->data();

      $bulan = Date('m',strtotime($input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL']));
      $tahun = Date('Y',strtotime($input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL']));

      $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_TERIMA = $input['KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_TERIMA'];

      $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_TERIMA = $input['KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_TERIMA'];

      $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_TERIMA = $input['KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_TERIMA'];

      $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_TERIMA = $input['KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_TERIMA'];

      $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_TERIMA = $input['KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_TERIMA'];

      $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_PAKAI = $input['KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_PAKAI'];

      $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_PAKAI = $input['KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_PAKAI'];

      $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_PAKAI = $input['KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_PAKAI'];

      $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_PAKAI = $input['KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_PAKAI'];

      $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_PAKAI = $input['KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_PAKAI'];

      $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_AKUMULASI = ($input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? 0 + $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_PAKAI : $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_AKUMULASI'] + $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_AKUMULASI = ($input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? 0 + $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_PAKAI : $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_AKUMULASI'] + $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_AKUMULASI = ($input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? 0 + $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_PAKAI : $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_AKUMULASI'] + $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_AKUMULASI = ($input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? 0 + $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_PAKAI : $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_AKUMULASI'] + $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_AKUMULASI = ($input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? 0 + $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_PAKAI : $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_AKUMULASI'] + $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_STOCK = $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_STOCK'] + $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_TERIMA - $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_STOCK = $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_STOCK'] + $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_TERIMA - $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_STOCK = $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_STOCK'] + $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_TERIMA - $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_STOCK = $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_STOCK'] + $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_TERIMA - $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_STOCK = $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_STOCK'] + $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_TERIMA - $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_PRE_EFFIENSI_CAUSTIC = $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_PAKAI / $result_f[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_LAPORAN']  * 100;

			if($input['KPE_AIR_FLOWMETER_KIMIA_PRE_ID']=="")
			{
				$sql_d = "SELECT KPE_AIR_FLOWMETER_KIMIA_PRE_ID FROM KPE_AIR_FLOWMETER_KIMIA_PRE WHERE KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL='".$input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL']."' AND RECORD_STATUS='A'";

				$this->MYSQL = new MYSQL();
				$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
				$this->MYSQL->queri = $sql_d;
				$result_d = $this->MYSQL->data();
				if ($result_d >= 1) {
					$this->callback['respon']['pesan'] = "gagal";
					$this->callback['respon']['text_msg'] = "Data ini sudah pernah diinput";
				} else {

					$sql_g = "SELECT KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL FROM KPE_AIR_FLOWMETER_KIMIA_PRE WHERE RECORD_STATUS='A' ORDER BY KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL DESC";

					$this->MYSQL = new MYSQL();
					$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
					$this->MYSQL->queri = $sql_g;
					$result_g = $this->MYSQL->data()[0]['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL'];
					$datesebelumnya = Date('Y/m/d',strtotime($result_g.'+1 day'));
					if ($datesebelumnya != $input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL']) {
						$this->callback['respon']['pesan'] = "gagal";
						$this->callback['respon']['text_msg'] = "Tanggal $datesebelumnya Belum terisi";
						$this->callback['result']= $result_g;
					} else {
						$data_master = array(
							'KPE_AIR_FLOWMETER_KIMIA_PRE_INDEX' => waktu_decimal(Date("Y-m-d H:i:s")),
							'KPE_AIR_FLOWMETER_KIMIA_PRE_ID' => waktu_decimal(Date("Y-m-d H:i:s")),
							'KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL' => $input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL'],
							'KPE_AIR_FLOWMETER_KIMIA_PRE_CODDING' => $input['KPE_AIR_FLOWMETER_KIMIA_PRE_CODDING'],
							'KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_TERIMA,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_TERIMA,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_TERIMA,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_TERIMA,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_TERIMA,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_PAKAI,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_PAKAI,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_PAKAI,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_PAKAI,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_PAKAI,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_AKUMULASI,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_AKUMULASI,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_AKUMULASI,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_AKUMULASI,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_AKUMULASI,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_AKUMULASI,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_STOCK' => $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_STOCK,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_STOCK' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_STOCK,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_STOCK' => $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_STOCK,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_STOCK' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_STOCK,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_STOCK' => $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_STOCK,
							'KPE_AIR_FLOWMETER_KIMIA_PRE_EFFIENSI_CAUSTIC' => round($KPE_AIR_FLOWMETER_KIMIA_PRE_EFFIENSI_CAUSTIC,1),
							'ENTRI_WAKTU' => date("Y-m-d H:i:s"),
							'ENTRI_OPERATOR' => $user_login['PERSONAL_NIK'],
							'RECORD_STATUS' => "A"
						);
			
						$this->MYSQL =new MYSQL;
						$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
						$this->MYSQL->tabel ="KPE_AIR_FLOWMETER_KIMIA_PRE";
						$this->MYSQL->record = $data_master;
			
						if ($this->MYSQL->simpan() == true)
						{
							$this->callback['respon']['pesan']="sukses";
							$this->callback['respon']['text_msg']="Data berhasil di simpan";
							$this->callback['result']=round($KPE_AIR_FLOWMETER_KIMIA_PRE_EFFIENSI_CAUSTIC,1);
						}
						else
						{
						$this->callback['respon']['pesan'] = "gagal";
						$this->callback['respon']['text_msg'] = "Data gagal di simpan";
						}
					}
				}
			}else 
			{
				$data_master_edit = array(
					
					'EDIT_WAKTU' => date("Y-m-d H:i:s"),
					'EDIT_OPERATOR' => $user_login['PERSONAL_NIK'],
					'RECORD_STATUS' => "E"
				);
	
				$this->MYSQL =new MYSQL;
				$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
				$this->MYSQL->tabel ="KPE_AIR_FLOWMETER_KIMIA_PRE";
				$this->MYSQL->record = $data_master_edit;
				$this->MYSQL->dimana = "WHERE KPE_AIR_FLOWMETER_KIMIA_PRE_ID='".$input['KPE_AIR_FLOWMETER_KIMIA_PRE_ID']."' AND RECORD_STATUS='A'";
	
				if ($this->MYSQL->ubah() == true)
				{
					$data_master = array(
						'KPE_AIR_FLOWMETER_KIMIA_PRE_INDEX' => waktu_decimal(Date("Y-m-d H:i:s")),
						'KPE_AIR_FLOWMETER_KIMIA_PRE_ID' => $input['KPE_AIR_FLOWMETER_KIMIA_PRE_ID'],
						'KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL' => $input['KPE_AIR_FLOWMETER_KIMIA_PRE_TANGGAL'],
						'KPE_AIR_FLOWMETER_KIMIA_PRE_CODDING' => $input['KPE_AIR_FLOWMETER_KIMIA_PRE_CODDING'],
						'KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_STOCK' => $KPE_AIR_FLOWMETER_KIMIA_PRE_HYDRO_STOCK,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_STOCK' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TAWAS_STOCK,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_STOCK' => $KPE_AIR_FLOWMETER_KIMIA_PRE_CAUSTIC_STOCK,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_STOCK' => $KPE_AIR_FLOWMETER_KIMIA_PRE_TCCA_STOCK,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_STOCK' => $KPE_AIR_FLOWMETER_KIMIA_PRE_POLIMER_STOCK,
						'KPE_AIR_FLOWMETER_KIMIA_PRE_EFFIENSI_CAUSTIC' => round($KPE_AIR_FLOWMETER_KIMIA_PRE_EFFIENSI_CAUSTIC,1),
						'ENTRI_WAKTU' => date("Y-m-d H:i:s"),
						'ENTRI_OPERATOR' => $user_login['PERSONAL_NIK'],
						'RECORD_STATUS' => "A"
					);
		
					$this->MYSQL =new MYSQL;
					$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
					$this->MYSQL->tabel ="KPE_AIR_FLOWMETER_KIMIA_PRE";
					$this->MYSQL->record = $data_master;
		
					if ($this->MYSQL->simpan() == true)
						{
							
								$this->callback['respon']['pesan']="sukses";
								$this->callback['respon']['text_msg']="Data berhasil di ubah";
								$this->callback['result']=$result;
						}
						else
						{
						$this->callback['respon']['pesan'] = "gagal";
						$this->callback['respon']['text_msg'] = "Data gagal di ubah";
						}
				}else {
					$this->callback['respon']['pesan'] = "gagal";
					$this->callback['respon']['text_msg'] = "Data gagal di ubah";
				}
			}
		
		


?>
