<?php

if (empty($params['case']))
	{
	$result['respon']['pesan'] == "gagal";
	$result['respon']['pesan'] == "Module tidak dapat di muat";
	echo json_encode($result);
	exit();
	}


			$input = $params['input_option'];

      $sql_e = "SELECT * FROM KPE_AIR_FLOWMETER_KIMIA_RO WHERE KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL='".$input['KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL_SEBELUMNYA']."' AND RECORD_STATUS='A'";

      $this->MYSQL = new MYSQL();
      $this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
      $this->MYSQL->queri = $sql_e;
      $result_e = $this->MYSQL->data();

      $bulan = Date('m',strtotime($input['KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL']));
      $tahun = Date('Y',strtotime($input['KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL']));

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_TERIMA = $input['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_TERIMA'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_TERIMA = $input['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_TERIMA'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_TERIMA = $input['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_TERIMA'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_TERIMA = $input['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_TERIMA'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_TERIMA = $input['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_TERIMA'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_TERIMA = $input['KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_TERIMA'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_PAKAI = $input['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_PAKAI'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_PAKAI = $input['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_PAKAI'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_PAKAI = $input['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_PAKAI'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_PAKAI = $input['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_PAKAI'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_PAKAI = $input['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_PAKAI'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_PAKAI = $input['KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_PAKAI'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_CAUSTIC_PAKAI = $input['KPE_AIR_FLOWMETER_KIMIA_RO_CAUSTIC_PAKAI'];

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_AKUMULASI = ($input['KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_PAKAI : $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_AKUMULASI'] + $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_AKUMULASI = ($input['KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_PAKAI : $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_AKUMULASI'] + $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_AKUMULASI = ($input['KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_PAKAI : $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_AKUMULASI'] + $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_AKUMULASI = ($input['KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_PAKAI : $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_AKUMULASI'] + $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_AKUMULASI = ($input['KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_PAKAI : $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_AKUMULASI'] + $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_AKUMULASI = ($input['KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_PAKAI : $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_AKUMULASI'] + $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_STOK = $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_STOK'] + $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_TERIMA - $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_STOK = $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_STOK'] + $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_TERIMA - $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_STOK = $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_STOK'] + $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_TERIMA - $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_STOK = $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_STOK'] + $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_TERIMA - $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_STOK = $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_STOK'] + $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_TERIMA - $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_PAKAI;

      $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_STOK = $result_e[0]['KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_STOK'] + $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_TERIMA - $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_PAKAI;

			if($input['KPE_AIR_FLOWMETER_KIMIA_PRE_ID']=="")
			{
				$sql_d = "SELECT KPE_AIR_FLOWMETER_KIMIA_PRE_ID FROM KPE_AIR_FLOWMETER_KIMIA_PRE WHERE KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL='".$input['KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL']."' AND RECORD_STATUS='A'";

				$this->MYSQL = new MYSQL();
				$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
				$this->MYSQL->queri = $sql_d;
				$result_d = $this->MYSQL->data();
				if ($result_d >= 1) {
					$this->callback['respon']['pesan'] = "gagal";
					$this->callback['respon']['text_msg'] = "Data ini sudah pernah diinput";
				} else {
					$data_master = array(
						'KPE_AIR_FLOWMETER_KIMIA_RO_INDEX' => waktu_decimal(Date("Y-m-d H:i:s")),
						'KPE_AIR_FLOWMETER_KIMIA_RO_ID' => waktu_decimal(Date("Y-m-d H:i:s")),
						'KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL' => $input['KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL'],
						'KPE_AIR_FLOWMETER_KIMIA_RO_CODDING' => $input['KPE_AIR_FLOWMETER_KIMIA_RO_CODDING'],
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_CAUSTIC_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_CAUSTIC_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_STOK' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_STOK,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_STOK' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_STOK,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_STOK' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_STOK,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_STOK' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_STOK,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_STOK' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_STOK,
						'KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_STOK' => $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_STOK,
						'ENTRI_WAKTU' => date("Y-m-d H:i:s"),
						'ENTRI_OPERATOR' => $user_login['PERSONAL_NIK'],
						'RECORD_STATUS' => "A"
					);
		
					$this->MYSQL =new MYSQL;
					$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
					$this->MYSQL->tabel ="KPE_AIR_FLOWMETER_KIMIA_RO";
					$this->MYSQL->record = $data_master;
		
					if ($this->MYSQL->simpan() == true)
					{
						$this->callback['respon']['pesan']="sukses";
						$this->callback['respon']['text_msg']="Data berhasil di simpan";
						$this->callback['result']=$result;
					}
					else
					{
					$this->callback['respon']['pesan'] = "gagal";
					$this->callback['respon']['text_msg'] = "Data gagal di simpan";
					}
				}
			}else 
			{
				$data_master_edit = array(
					
					'EDIT_WAKTU' => date("Y-m-d H:i:s"),
					'EDIT_OPERATOR' => $user_login['PERSONAL_NIK'],
					'RECORD_STATUS' => "E"
				);
	
				$this->MYSQL =new MYSQL;
				$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
				$this->MYSQL->tabel ="KPE_AIR_FLOWMETER_KIMIA_RO";
				$this->MYSQL->record = $data_master_edit;
				$this->MYSQL->dimana = "WHERE KPE_AIR_FLOWMETER_KIMIA_RO_ID='".$input['KPE_AIR_FLOWMETER_KIMIA_RO_ID']."' AND RECORD_STATUS='A'";
	
				if ($this->MYSQL->ubah() == true)
				{
					$data_master = array(
						'KPE_AIR_FLOWMETER_KIMIA_RO_INDEX' => waktu_decimal(Date("Y-m-d H:i:s")),
						'KPE_AIR_FLOWMETER_KIMIA_RO_ID' => waktu_decimal(Date("Y-m-d H:i:s")),
						'KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL' => $input['KPE_AIR_FLOWMETER_KIMIA_RO_TANGGAL'],
						'KPE_AIR_FLOWMETER_KIMIA_RO_CODDING' => $input['KPE_AIR_FLOWMETER_KIMIA_RO_CODDING'],
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_TERIMA' => $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_TERIMA,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_CAUSTIC_PAKAI' => $KPE_AIR_FLOWMETER_KIMIA_RO_CAUSTIC_PAKAI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_AKUMULASI' => $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_AKUMULASI,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_STOK' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_590_STOK,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_STOK' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_277_STOK,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_STOK' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_566_STOK,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_STOK' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_259_STOK,
						'KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_STOK' => $KPE_AIR_FLOWMETER_KIMIA_RO_HYDRO_575_STOK,
						'KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_STOK' => $KPE_AIR_FLOWMETER_KIMIA_RO_GARAM_STOK,
						'ENTRI_WAKTU' => date("Y-m-d H:i:s"),
						'ENTRI_OPERATOR' => $user_login['PERSONAL_NIK'],
						'RECORD_STATUS' => "A"
					);
		
					$this->MYSQL =new MYSQL;
					$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
					$this->MYSQL->tabel ="KPE_AIR_FLOWMETER_KIMIA_RO";
					$this->MYSQL->record = $data_master;
		
					if ($this->MYSQL->simpan() == true)
						{
							
								$this->callback['respon']['pesan']="sukses";
								$this->callback['respon']['text_msg']="Data berhasil di ubah";
								$this->callback['result']=$result;
						}
						else
						{
						$this->callback['respon']['pesan'] = "gagal";
						$this->callback['respon']['text_msg'] = "Data gagal di ubah";
						}
				}else {
					$this->callback['respon']['pesan'] = "gagal";
					$this->callback['respon']['text_msg'] = "Data gagal di ubah";
				}
			}
		
		


?>
