<?php

if (empty($params['case']))
	{
	$result['respon']['pesan'] == "gagal";
	$result['respon']['pesan'] == "Module tidak dapat di muat";
	echo json_encode($result);
	exit();
	}


		$input = $params['input_option'];

		$sql_c = "SELECT * FROM KPE_AIR_FLOWMETER_OPERASIONAL_RO WHERE KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL='".$input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL_SEBELUMNYA']."' AND RECORD_STATUS='A'";

		$this->MYSQL = new MYSQL();
		$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
		$this->MYSQL->queri = $sql_c;
		$result_c = $this->MYSQL->data();

		$sql_g = "SELECT * FROM KPE_AIR_FLOWMETER_REKAP_USED_PRE 
							WHERE KPE_AIR_FLOWMETER_REKAP_USED_PRE_TANGGAL='".$input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL']."' 
							AND RECORD_STATUS='A' 
							AND KPE_AIR_FLOWMETER_ID = '20210131083054838872'";

		$this->MYSQL = new MYSQL();
		$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
		$this->MYSQL->queri = $sql_g;
		$result_g = $this->MYSQL->data();

		$sql_h = "SELECT * FROM KPE_AIR_FLOWMETER_REKAP_USED_RO 
							WHERE KPE_AIR_FLOWMETER_REKAP_USED_RO_TANGGAL='".$input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL']."' 
							AND RECORD_STATUS='A'";

		$this->MYSQL = new MYSQL();
		$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
		$this->MYSQL->queri = $sql_h;
		$result_h = $this->MYSQL->data()[0];

		$bulan = date('m',strtotime($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL']));
		$tahun = date('Y',strtotime($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL']));

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_1 = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_1'];
		
		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_HASIL_LINE_1 = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_1'] - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_1'];
		
		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_2 = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_2'];
		
		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_HASIL_LINE_2 = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_2'] - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_2'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_1 = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_1'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_HASIL_LINE_1 = ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_1 == "") ? 0 : round(($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_1']-$result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_1']),3);

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_2 = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_2'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_HASIL_LINE_2 = ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_2 == "") ? 0 : round(($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_2']-$result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_2']),3);

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_TOTAL = $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_HASIL_LINE_1 + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_HASIL_LINE_2 + $result_g[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_REJECT'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_AKUMULASI = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? 0 + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_TOTAL : $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_AKUMULASI'] + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_TOTAL;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1 = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1'];

		if ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1 == $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1']) {
			$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1 = 0;
		} else {
			if ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1 == '0') {
				$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1 = 0;
			} else {
				if ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') {
					$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1 = round(($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1 - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1'] + 0),3);
				} else {
					$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1 = round(($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1 - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1'] + $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1']),3);
				}
			}
		}

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_AKUMULASI_1 = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1 + 0 : $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1 + $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1'] ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1 = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1'];

		if ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1 == $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1']) {
			$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1 = 0;
		} else {
			if ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1 == '0') {
				$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1 = 0;
			} else {
				if ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') {
					$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1 = round(($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1 - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1'] + 0),3);
				} else {
					$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1 = round(($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1 - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1'] + $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1']),3);
				}
			}
		}

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_AKUMULASI_1 = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1 + 0 : $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1 + $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1'] ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_1 = round(($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1 - $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1),3);

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_AKUMULASI_1 = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_1 : $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_1 + $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_AKUMULASI_1'] ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_1 = 0.98 * $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_1'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_1 = ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_1 == '0') ? 0 : round($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1 / $KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_1 ,3);

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_AKUMULASI_1 = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_1 + 0 : $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_AKUMULASI_1'] + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_1;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2 = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2'];

		if ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2 == $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2']) {
			$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2 = 0;
		} else {
			if ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2 == '0') {
				$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2 = 0;
			} else {
				if ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') {
					$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2 = round(($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2 - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2'] + 0),3);
				} else {
					$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2 = round(($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2 - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2'] + $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2']),3);
				}
			}
		}

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_AKUMULASI_2 = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2 + 0 : $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2 + $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2'] ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2 = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2'];

		if ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2 == $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2']) {
			$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2 = '';
		} else {
			if ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2 == '') {
				$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2 = '';
			} else {
				if ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') {
					$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2 = round(($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2 - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2']),3);
				} else {
					$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2 = round(($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2 - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2'] + $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2']),3);
				}
			}
		}

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_AKUMULASI_2 = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2 + 0 : $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2 + $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2'] ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_2 = round(($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2 - $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2),3);

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_AKUMULASI_2 = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_2 + 0 : $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_2 + $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_2_AKUMULASI'] ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_2 = 0.06 * 0.98 * $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_2'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_2 = ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_2 == '0') ? 0 : round($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2 / $KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_2 ,3);

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_AKUMULASI_2 = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_2 + 0 : $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_AKUMULASI_2'] + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_2;
		
		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_TOTAL = $result_g[0]['KPE_AIR_FLOWMETER_REKAP_USED_PRE_BEBAN'] - $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_TOTAL ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_AKUMULASI = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_TOTAL : $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_AKUMULASI'] + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_TOTAL;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_CARBON_FILTER = $result_g[0]['KPE_AIR_FLOWMETER_REKAP_USED_PRE_BEBAN'];

		//! BELUM DI GUNAKAN
		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_FLOW = 0;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_PRODUK = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_FLOW - 0 : $KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_FLOW - $KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_FLOW;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_AKUMULASI = 0;
		//! END

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_PRODUK = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? 0 + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2 + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1 : $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_PRODUK'] + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2 + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT = $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_2 + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_1 ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT_HASIL = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? 0 + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT : $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT_HASIL'] + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_EFFESIENSI_PROSES_1 = ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1 == '0') ? 0 : $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1 / $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1 * 100 ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_EFFESIENSI_PROSES_2 = ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2 == '0') ? 0 : $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2 / $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2 * 100 ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_HASIL_PROSES_PRODUK = ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2 + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1) / ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2 + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1) * 100;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_1 = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_1'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_2 = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_2'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BAK_IV = (2.9 - $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BAK_IV']) * 15 * 13;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_I = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_I'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_II = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_II'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_III = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_III'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_IV = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_IV'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_V_SEKAT = $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_V_SEKAT'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_SOFT_WATER_1 = ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_1 == "") ? 0 : round(2.25*(390-$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_1),2);

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_SOFT_WATER_2 = ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_2 == "") ? 0 : round(2.25*(390-$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_2),2);

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TANKI = $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BAK_IV;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_I = ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_I == "") ? 0 : round(2.64*(300-$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_I),2);

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_II = round(2.71*(300-$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_II),2);
		
		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_III = ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_III == "") ? 0 : round(2.48*(300-$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_III),2);
		
		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_IV = round(2.42*(300-$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_IV),2);

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_V_SEKAT = ($KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_V_SEKAT == "") ? 0 : round(5.358*(290-$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_V_SEKAT)-247.95,2);

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TOTAL = $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_SOFT_WATER_1 + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_SOFT_WATER_2 + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TANKI + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_I + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_II + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_III + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_IV + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_V_SEKAT;

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_SUSUT = $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TOTAL'] - $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TOTAL + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_TOTAL - $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_1 - $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_2 - $result_h['KPE_AIR_FLOWMETER_REKAP_USED_RO_TOTAL'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_KONTROL_SUSUT = round($KPE_AIR_FLOWMETER_OPERASIONAL_RO_SUSUT / $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_CARBON_FILTER,5);

		$KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_SUSUT = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? 0 + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SUSUT : $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_SUSUT'] + $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SUSUT;

		if($input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_ID']=="")
		{
			$sql_d = "SELECT * FROM KPE_AIR_FLOWMETER_OPERASIONAL_RO WHERE KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL='".$input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL']."' AND RECORD_STATUS='A'";

			$this->MYSQL = new MYSQL();
			$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
			$this->MYSQL->queri = $sql_d;
			$result_d = $this->MYSQL->data();
			if ($result_d >= 1) {
				$this->callback['respon']['pesan'] = "gagal";
				$this->callback['respon']['text_msg'] = "Data ditanggal ini sudah diinput";
			} else {

				$data_master = array(
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_INDEX' => waktu_decimal(Date("Y-m-d H:i:s")),
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_ID' => waktu_decimal(Date("Y-m-d H:i:s")),
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_CODDING' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_CODDING'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_HASIL_LINE_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_HASIL_LINE_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_HASIL_LINE_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_HASIL_LINE_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_TOTAL' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_TOTAL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_AKUMULASI' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_AKUMULASI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_HASIL_LINE_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_HASIL_LINE_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_HASIL_LINE_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_HASIL_LINE_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_TOTAL' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_TOTAL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_AKUMULASI' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_AKUMULASI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_AKUMULASI_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_AKUMULASI_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_AKUMULASI_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_AKUMULASI_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_AKUMULASI_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_AKUMULASI_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_AKUMULASI_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_AKUMULASI_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_AKUMULASI_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_AKUMULASI_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_AKUMULASI_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_AKUMULASI_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_AKUMULASI_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_AKUMULASI_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_AKUMULASI_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_AKUMULASI_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_CARBON_FILTER' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_CARBON_FILTER,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_FLOW' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_FLOW,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_PRODUK' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_PRODUK,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_AKUMULASI' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_AKUMULASI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SUSUT' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SUSUT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_KONTROL_SUSUT' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_KONTROL_SUSUT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_SUSUT' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_SUSUT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_PRODUK' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_PRODUK,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT_HASIL' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT_HASIL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_EFFESIENSI_PROSES_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_EFFESIENSI_PROSES_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_EFFESIENSI_PROSES_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_EFFESIENSI_PROSES_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_HASIL_PROSES_PRODUK' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_HASIL_PROSES_PRODUK,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BAK_IV' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BAK_IV,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_I' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_I,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_II' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_II,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_III' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_III,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_IV' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_IV,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_V_SEKAT' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_V_SEKAT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TOTAL' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TOTAL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_SOFT_WATER_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_SOFT_WATER_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_SOFT_WATER_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_SOFT_WATER_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TANKI' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TANKI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_I' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_I,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_II' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_II,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_III' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_III,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_IV' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_IV,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_V_SEKAT' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_V_SEKAT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_1_INPUT' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_1'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_2_INPUT' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_2'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BAK_IV_INPUT' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BAK_IV'],
					'ENTRI_WAKTU' => date("Y-m-d H:i:s"),
					'ENTRI_OPERATOR' => $user_login['PERSONAL_NIK'],
					'RECORD_STATUS' => "A"
				);

				$this->MYSQL =new MYSQL;
				$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
				$this->MYSQL->tabel ="KPE_AIR_FLOWMETER_OPERASIONAL_RO";
				$this->MYSQL->record = $data_master;

				if ($this->MYSQL->simpan() == true)
				{
					$this->callback['respon']['pesan']="sukses";
					$this->callback['respon']['text_msg']="Data Berhasil Disimpan";
					$this->callback['result']=$KPE_AIR_FLOWMETER_OPERASIONAL_RO_KONTROL_SUSUT;
				}
				else
				{
					$this->callback['respon']['pesan'] = "gagal";
					$this->callback['respon']['text_msg'] = "Data Gagal Disimpan";
				}
			}
		}else 
		{
			$data_master_edit = array(
				
				'EDIT_WAKTU' => date("Y-m-d H:i:s"),
				'EDIT_OPERATOR' => $user_login['PERSONAL_NIK'],
				'RECORD_STATUS' => "E"
			);

			$this->MYSQL =new MYSQL;
			$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
			$this->MYSQL->tabel ="KPE_AIR_FLOWMETER_OPERASIONAL_RO";
			$this->MYSQL->record = $data_master_edit;
			$this->MYSQL->dimana = "WHERE KPE_AIR_FLOWMETER_OPERASIONAL_RO_ID='".$input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_ID']."' AND RECORD_STATUS='A'";

			if ($this->MYSQL->ubah() == true)
			{
				$data_master_ubah = array(
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_INDEX' => waktu_decimal(Date("Y-m-d H:i:s")),
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_ID' => waktu_decimal(Date("Y-m-d H:i:s")),
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_CODDING' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_CODDING'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_TANGGAL'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_HASIL_LINE_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_HASIL_LINE_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_FLOW_LINE_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_HASIL_LINE_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_HASIL_LINE_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_TOTAL' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_TOTAL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_AKUMULASI' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOFTENER_AKUMULASI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_HASIL_LINE_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_HASIL_LINE_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_FLOW_LINE_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_HASIL_LINE_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_HASIL_LINE_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_TOTAL' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_TOTAL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_AKUMULASI' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REGENERASI_AKUMULASI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_AKUMULASI_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_AKUMULASI_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_AKUMULASI_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_AKUMULASI_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_AKUMULASI_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_AKUMULASI_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_AKUMULASI_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_AKUMULASI_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_FLOW_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_HASIL_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_AKUMULASI_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_AKUMULASI_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_FLOW_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_HASIL_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_AKUMULASI_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PRODUK_AKUMULASI_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_AKUMULASI_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_REJECT_AKUMULASI_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_AKUMULASI_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_WAKTU_OPERASI_AKUMULASI_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_CARBON_FILTER' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_PROSES_CARBON_FILTER,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_FLOW' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_FLOW,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_PRODUK' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_PRODUK,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_AKUMULASI' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_BACKWASH_AKUMULASI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SUSUT' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SUSUT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_KONTROL_SUSUT' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_KONTROL_SUSUT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_SUSUT' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_SUSUT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_PRODUK' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_PRODUK,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT_HASIL' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_AKUMULASI_REJECT_HASIL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_EFFESIENSI_PROSES_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_EFFESIENSI_PROSES_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_EFFESIENSI_PROSES_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_EFFESIENSI_PROSES_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_HASIL_PROSES_PRODUK' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_HASIL_PROSES_PRODUK,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_SOFT_WATER_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BAK_IV' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BAK_IV,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_I' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_I,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_II' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_II,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_III' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_III,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_IV' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_IV,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_V_SEKAT' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BOILER_V_SEKAT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TOTAL' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TOTAL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_SOFT_WATER_1' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_SOFT_WATER_1,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_SOFT_WATER_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_SOFT_WATER_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TANKI' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_TANKI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_I' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_I,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_II' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_II,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_III' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_III,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_IV' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_IV,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_V_SEKAT' => $KPE_AIR_FLOWMETER_OPERASIONAL_RO_STOK_BOILER_V_SEKAT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_1_INPUT' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_1'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_2_INPUT' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_DEBIT_PRODUK_2'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BAK_IV_INPUT' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_RO_SOUNDING_BAK_IV'],
					'ENTRI_WAKTU' => date("Y-m-d H:i:s"),
					'ENTRI_OPERATOR' => $user_login['PERSONAL_NIK'],
					'RECORD_STATUS' => "A"
				);
	
				$this->MYSQL =new MYSQL;
				$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
				$this->MYSQL->tabel ="KPE_AIR_FLOWMETER_OPERASIONAL_RO";
				$this->MYSQL->record = $data_master_ubah;
	
				if ($this->MYSQL->simpan() == true)
					{
						
							$this->callback['respon']['pesan']="sukses";
							$this->callback['respon']['text_msg']="Data Berhasil Diubah";
							$this->callback['result']=$result;
					}
					else
					{
					$this->callback['respon']['pesan'] = "gagal";
					$this->callback['respon']['text_msg'] = "Data Gagal Diubah";
					}
			}else {
				$this->callback['respon']['pesan'] = "gagal";
				$this->callback['respon']['text_msg'] = "Data Gagal Diubah";
			}
		}
		
		


?>
