<?php

if (empty($params['case']))
	{
	$result['respon']['pesan'] == "gagal";
	$result['respon']['pesan'] == "Module tidak dapat di muat";
	echo json_encode($result);
	exit();
	}


		$input = $params['input_option'];

		$sql_c = "SELECT * FROM KPE_AIR_FLOWMETER_OPERASIONAL_PRE WHERE KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL='".$input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL_SEBELUMNYA']."' AND RECORD_STATUS='A'";

		$this->MYSQL = new MYSQL();
		$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
		$this->MYSQL->queri = $sql_c;
		$result_c = $this->MYSQL->data();

		$sql_g = "SELECT * FROM KPE_AIR_FLOWMETER_REKAP_USED_PRE 
							WHERE KPE_AIR_FLOWMETER_REKAP_USED_PRE_TANGGAL='".$input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL']."' 
							AND RECORD_STATUS='A' 
							AND KPE_AIR_FLOWMETER_ID = '20210131083054838872'";

		$this->MYSQL = new MYSQL();
		$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
		$this->MYSQL->queri = $sql_g;
		$result_g = $this->MYSQL->data();

		$sql_e = "SELECT SUM(KPE_AIR_FLOWMETER_REKAP_USED_PRE_BEBAN) AS KPE_AIR_FLOWMETER_REKAP_USED_PRE_BEBAN FROM KPE_AIR_FLOWMETER_REKAP_USED_PRE 
							WHERE KPE_AIR_FLOWMETER_REKAP_USED_PRE_TANGGAL='".$input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL']."' 
							AND RECORD_STATUS='A' 
							AND KPE_AIR_FLOWMETER_ID IN ('20210109143041548749','20210109143155699461')";

		$this->MYSQL = new MYSQL();
		$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
		$this->MYSQL->queri = $sql_e;
		$result_e = $this->MYSQL->data();

		$bulan = date('m',strtotime($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL']));
		$tahun = date('Y',strtotime($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL']));

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_1_2'] != "") ? round((($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_1_2']-$result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_1_2'])-($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_1_2']-$result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_1_2'])*0/100),3)*10 : "" ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUM_PROSES_CC_1_2_LAPORAN = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL'] != $tahun.'/'.$bulan.'/01') ? $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUM_PROSES_CC_1_2_LAPORAN'] + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL : $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL ;
		
		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_RW = $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_RW'] + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL + ($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_3_4'] - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_3_4']) + $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_RW_PENGKONDISIAN'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW = $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_RW - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_RW'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_RW = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL'] != $tahun.'/'.$bulan.'/01') ? $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_RW'] + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW  : $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL = $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUM_PROSES_CC_3_4_LAPORAN = ($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL != "") ? $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUM_PROSES_CC_3_4_LAPORAN'] + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL : "" ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_REAL = round(($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL),3);

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_LAPORAN = round(($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL),3);

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_CC_LAPORAN = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_LAPORAN + 0 : round(($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_LAPORAN + $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_CC_LAPORAN']),3);

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI_HASIL_RUMUS = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI'] != "") ? $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI'] - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI'] + $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI_PENGKONDISIAN'] : "" ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_PRODUKSI = $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI_HASIL_RUMUS;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI_PENGKONDISIAN = $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI_PENGKONDISIAN'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CARBON_FILTER = $result_g[0]['KPE_AIR_FLOWMETER_REKAP_USED_PRE_BEBAN'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_MESS = $result_e[0]['KPE_AIR_FLOWMETER_REKAP_USED_PRE_BEBAN'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_DRAIN_BACKWASH = 0;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PROSES_PRE_RO_RUMUS = $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PROSES_PRE_RO'] - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PROSES_PRE_RO'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUK_PRE_RO_RUMUS = $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUK_PRE_RO'] - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUK_PRE_RO'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_PRE = ($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_PRODUKSI + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CARBON_FILTER + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_MESS) - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_DRAIN_BACKWASH + KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PROSES_PRE_RO;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_PRE = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_PRE : $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_PRE'] + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_PRE;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_EFFESIENSI = ($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_LAPORAN != "") ? $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_PRE/$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW*100 : "" ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI = $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI'];

		// $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PROSES_PRE = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI - 0 + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_PRE : ($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI != "") ? $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI'] + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_PRE : "" ;
		if ($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL'] == $tahun.'/'.$bulan.'/01') {
			$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PROSES_PRE = $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI - 0 + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_PRE;
		} else {
			if ($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI != "") {
				$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PROSES_PRE = $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI - $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI'] + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_PRE;
			}else {
				$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PROSES_PRE = '';
			}
		}

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PAKAI_PRE = $result_g[0]['KPE_AIR_FLOWMETER_REKAP_USED_PRE_TOTAL'] - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CARBON_FILTER - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_MESS - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_DRAIN_BACKWASH;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_STOCK = $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_EMPLOYE_MESS_BASIN'] + $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOWER'] + $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AERASI_BASIN'] + $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FILTERED_WATER_BASIN'] + $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_BAK_BSF_1_2'] + $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_BAK_BSF_3_4'] + $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI'];

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_DISTRIBUSI = $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CARBON_FILTER + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_MESS + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PAKAI_PRE;
		
		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PRE_DISTRIBUSI = ($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW != "") ? $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_STOCK'] - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_STOCK + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_DISTRIBUSI - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_DRAIN_BACKWASH : "";

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2 = ($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL != "") ? $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL/30/2 : "" ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2_RUMUS = ($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL != "") ? $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL/30/2 : "" ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4 = ($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL != "") ? $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL/38/2 : "" ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4_RUMUS = ($KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL != "") ? $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL/38/2 : "" ;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_3 = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2 + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2_RUMUS : $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_3'] + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2 + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2_RUMUS;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_6 = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4 + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4_RUMUS : $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_6'] + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4 + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4_RUMUS;

		$KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT = ($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL'] == $tahun.'/'.$bulan.'/01') ? $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PRE_DISTRIBUSI : $result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT'] + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PRE_DISTRIBUSI ;

	
		if($input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_ID']=="")
		{
			$sql_d = "SELECT * FROM KPE_AIR_FLOWMETER_OPERASIONAL_PRE WHERE KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL='".$input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL']."' AND RECORD_STATUS='A'";

			$this->MYSQL = new MYSQL();
			$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
			$this->MYSQL->queri = $sql_d;
			$result_d = $this->MYSQL->data();
			if ($result_d >= 1) {
				$this->callback['respon']['pesan'] = "gagal";
				$this->callback['respon']['text_msg'] = "Data ditanggal ini sudah diinput";
			} else {

				$data_master = array(
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_INDEX' => waktu_decimal(Date("Y-m-d H:i:s")),
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_ID' => waktu_decimal(Date("Y-m-d H:i:s")),
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CODDING' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CODDING'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_RW' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_RW,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_RW' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_RW,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_1_2' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_1_2'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUM_PROSES_CC_1_2_LAPORAN' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUM_PROSES_CC_1_2_LAPORAN,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_3_4' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_3_4'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUM_PROSES_CC_3_4_LAPORAN' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUM_PROSES_CC_3_4_LAPORAN,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_REAL' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_REAL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_LAPORAN' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_LAPORAN,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_CC_LAPORAN' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_CC_LAPORAN,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI_HASIL_RUMUS' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI_HASIL_RUMUS,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI_PENGKONDISIAN' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI_PENGKONDISIAN,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_PRODUKSI' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_PRODUKSI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CARBON_FILTER' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CARBON_FILTER,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_MESS' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_MESS,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_DRAIN_BACKWASH' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_DRAIN_BACKWASH,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_PRE' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_PRE,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_PRE' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_PRE,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_EFFESIENSI' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_EFFESIENSI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PROSES_PRE' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PROSES_PRE,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PAKAI_PRE' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PAKAI_PRE,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PRE_DISTRIBUSI' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PRE_DISTRIBUSI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_DISTRIBUSI' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_DISTRIBUSI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_EMPLOYE_MESS_BASIN' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_EMPLOYE_MESS_BASIN'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOWER' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOWER'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AERASI_BASIN' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AERASI_BASIN'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FILTERED_WATER_BASIN' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FILTERED_WATER_BASIN'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_BAK_BSF_1_2' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_BAK_BSF_1_2'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_BAK_BSF_3_4' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_BAK_BSF_3_4'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_STOCK' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_STOCK,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2_RUMUS' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2_RUMUS,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4_RUMUS' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4_RUMUS,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_3' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_3,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_6' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_6,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PROSES_PRE_RO' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PROSES_PRE_RO'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PROSES_PRE_RO_RUMUS' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PROSES_PRE_RO_RUMUS,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUK_PRE_RO' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUK_PRE_RO'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUK_PRE_RO_RUMUS' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUK_PRE_RO_RUMUS,
					'ENTRI_WAKTU' => date("Y-m-d H:i:s"),
					'ENTRI_OPERATOR' => $user_login['PERSONAL_NIK'],
					'RECORD_STATUS' => "A"
				);

				$this->MYSQL =new MYSQL;
				$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
				$this->MYSQL->tabel ="KPE_AIR_FLOWMETER_OPERASIONAL_PRE";
				$this->MYSQL->record = $data_master;

				if ($this->MYSQL->simpan() == true)
				{
					$this->callback['respon']['pesan']="sukses";
					$this->callback['respon']['text_msg']="Data Berhasil Disimpan";
					$this->callback['result']=$result_c[0]['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_STOCK'] - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_STOCK + $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_DISTRIBUSI - $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_DRAIN_BACKWASH;
				}
				else
				{
					$this->callback['respon']['pesan'] = "gagal";
					$this->callback['respon']['text_msg'] = "Data Gagal Disimpan";
				}
			}
		}else 
		{
			$data_master_edit = array(
				
				'EDIT_WAKTU' => date("Y-m-d H:i:s"),
				'EDIT_OPERATOR' => $user_login['PERSONAL_NIK'],
				'RECORD_STATUS' => "E"
			);

			$this->MYSQL =new MYSQL;
			$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
			$this->MYSQL->tabel ="KPE_AIR_FLOWMETER_OPERASIONAL_PRE";
			$this->MYSQL->record = $data_master_edit;
			$this->MYSQL->dimana = "WHERE KPE_AIR_FLOWMETER_OPERASIONAL_PRE_ID='".$input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_ID']."' AND RECORD_STATUS='A'";

			if ($this->MYSQL->ubah() == true)
			{
				$data_master_ubah = array(
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_INDEX' => waktu_decimal(Date("Y-m-d H:i:s")),
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_ID' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_ID'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CODDING' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CODDING'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TANGGAL'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_RW' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_RW,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_RW,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_RW' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_RW,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_1_2' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_1_2'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_1_2_REAL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUM_PROSES_CC_1_2_LAPORAN' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUM_PROSES_CC_1_2_LAPORAN,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_3_4' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_CC_3_4'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_CC_3_4_REAL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUM_PROSES_CC_3_4_LAPORAN' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUM_PROSES_CC_3_4_LAPORAN,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_REAL' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_REAL,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_LAPORAN' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_CC_LAPORAN,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_CC_LAPORAN' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_CC_LAPORAN,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI_HASIL_RUMUS' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUKSI_HASIL_RUMUS,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_PRODUKSI' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PROSES_PRODUKSI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CARBON_FILTER' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CARBON_FILTER,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_MESS' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_MESS,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_DRAIN_BACKWASH' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_DRAIN_BACKWASH,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_PRE' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_PROSES_PRE,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_PRE' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_PROSES_PRE,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_EFFESIENSI' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_EFFESIENSI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_STOCK_BAK_EQUALISASI'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PROSES_PRE' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PROSES_PRE,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PAKAI_PRE' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_PAKAI_PRE,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PRE_DISTRIBUSI' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT_PRE_DISTRIBUSI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_DISTRIBUSI' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOTAL_DISTRIBUSI,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_EMPLOYE_MESS_BASIN' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_EMPLOYE_MESS_BASIN'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOWER' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_TOWER'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AERASI_BASIN' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AERASI_BASIN'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FILTERED_WATER_BASIN' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FILTERED_WATER_BASIN'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_BAK_BSF_1_2' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_BAK_BSF_1_2'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_BAK_BSF_3_4' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_BAK_BSF_3_4'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_STOCK' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_AKUMULASI_STOCK,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2_RUMUS' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_2_RUMUS,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4_RUMUS' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_4_RUMUS,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_3' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_1_3,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_6' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_CC_3_6,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_SUSUT,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PROSES_PRE_RO' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PROSES_PRE_RO'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PROSES_PRE_RO_RUMUS' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PROSES_PRE_RO_RUMUS,
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUK_PRE_RO' => $input['KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUK_PRE_RO'],
					'KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUK_PRE_RO_RUMUS' => $KPE_AIR_FLOWMETER_OPERASIONAL_PRE_FLOW_PRODUK_PRE_RO_RUMUS,
					'ENTRI_WAKTU' => date("Y-m-d H:i:s"),
					'ENTRI_OPERATOR' => $user_login['PERSONAL_NIK'],
					'RECORD_STATUS' => "A"
				);
	
				$this->MYSQL =new MYSQL;
				$this->MYSQL->database = $this->CONFIG->mysql_koneksi()->db_nama;
				$this->MYSQL->tabel ="KPE_AIR_FLOWMETER_OPERASIONAL_PRE";
				$this->MYSQL->record = $data_master_ubah;
	
				if ($this->MYSQL->simpan() == true)
					{
						
							$this->callback['respon']['pesan']="sukses";
							$this->callback['respon']['text_msg']="Data Berhasil Diubah";
							$this->callback['result']=$result;
					}
					else
					{
					$this->callback['respon']['pesan'] = "gagal";
					$this->callback['respon']['text_msg'] = "Data Gagal Diubah";
					}
			}else {
				$this->callback['respon']['pesan'] = "gagal";
				$this->callback['respon']['text_msg'] = "Data Gagal Diubah";
			}
		}
		
		


?>
